# Configuration for pre-commit hooks (see https://pre-commit.com/).
# Eventually the hooks described here will be run as tests before merging each PR.

# TODO: remove global exclusion of tests when testing overhaul is complete
exclude: ^test/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude_types:
          - "markdown"
      - id: check-case-conflict
  - repo: https://github.com/dbt-labs/pre-commit-hooks
    rev: v0.1.0a1
    hooks:
      - id: dbt-core-in-adapters-check
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - "--line-length=99"
          - "--target-version=py38"
      - id: black
        alias: black-check
        stages: [manual]
        args:
          - "--line-length=99"
          - "--target-version=py38"
          - "--check"
          - "--diff"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
      - id: flake8
        alias: flake8-check
        stages: [manual]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        # N.B.: Mypy is... a bit fragile.
        #
        # By using `language: system` we run this hook in the local
        # environment instead of a pre-commit isolated one.  This is needed
        # to ensure mypy correctly parses the project.

        # It may cause trouble in that it adds environmental variables out
        # of our control to the mix.  Unfortunately, there's nothing we can
        # do about per pre-commit's author.
        # See https://github.com/pre-commit/pre-commit/issues/730 for details.
        args: [ --show-error-codes, --ignore-missing-imports ]
        files: ^dbt/adapters/.*
        language: system
      - id: mypy
        alias: mypy-check
        stages: [ manual ]
        args: [ --show-error-codes, --pretty, --ignore-missing-imports ]
        files: ^dbt/adapters
        language: system
