FROM openjdk:16-ea-17

RUN apt-get update && \
  apt-get install -yf postgresql-client netcat && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY wait_for_up.bash /bin/wait_for_up
RUN chmod +x /bin/wait_for_up
